### ISSUE TITLE
Staking issue

### ISSUE THREAD

**Issue by Mechwarrior20** [haqq-network/haqq-wallet#1655]
## Expected Behavior

Using staking feature native to Haqq Wallet be able to stake. 

## Actual Behavior

Staking does not occur with error stgf

Also gas fee charged seem to be .07192373 which seems a little high, staking 500k. 

## Steps to Reproduce the Problem

Normal pathway to staking in Haqq Wallet selecting Emir Validator. 

## Specifications

- Build number: v1.5.4 (378)
- Platform: iPhone Pro Max 15
- OS Version: 17.3.1

**Comment by ragozin-nikita** [comment]
Please contact our CS on [Discord](https://discord.gg/islamiccoin)
