### ISSUE TITLE
[Андроид, Баг] По какой-то причине не крутится анимация при заходе в приложение

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#199]
Иногда работает, но в большинстве случаев статичная картинка как на скрине ниже (модель Xiaomi Redmi 9C, на основе android 11)

![Image](https://user-images.githubusercontent.com/114990952/196374204-8352b4f5-556b-4712-ba3f-17e810ddff86.jpg)

**Comment by vivalaakam** [comment]
Статичная картинка показывается пока загружается приложение, как только оно загружено, запускается анимация
