### ISSUE TITLE
[Андроид, Баги] Страница отправки

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#206]
[x] Есть баг на андроиде что зеленая линия ввода отображается прям посередине 0
[] Если зайти на страницу ввода суммы, потом убрать клавиатуру (например перейдя на предыдущую страницу), а потом вызвать клавиатуру обратно то кнопка Preview слетает

![Image](https://user-images.githubusercontent.com/114990952/196419308-409a8486-760f-4198-886a-f59f993af7d6.jpg)

![Image](https://user-images.githubusercontent.com/114990952/196419969-e462c929-d83c-4391-9600-579f31fcdf8b.jpg) 

![Image](https://user-images.githubusercontent.com/114990952/196420076-87f87c16-8da1-43d3-9f0c-0b93d7611f6e.jpg)

**Comment by gHashTag** [comment]
Необходимо сделать рефакторинг кнопки Button
