### ISSUE TITLE
Темная тема

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#279]
Пункт Appearance темы появился в настройках (по дефолту системное) https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/Wallet?node-id=591%3A17052

Открытая страница настройки https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/Wallet?node-id=2250%3A45079

Все экраны в темной версии (ссылки на анимации тоже обновлены на актуальные темные версии) https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/Wallet?node-id=1547%3A27021

Тут все пары цветов которые заменяют друг друга https://www.figma.com/file/hVISlIFIJFPsnhlVmpNxrR/Style?node-id=0%3A1

**Comment by YuriySherbak** [comment]
Места в которых темного стиля нет:
1. Иконка сканирования должна быть светлая
2. Кнопка закрытия должна быть темная
3. На первом табе не отображается активный выбор, во втором табе неактивный таб не виден
4. У тайтла цвет не тот и у иконки
5. Добавление контакта другого цвета
6. Контакты другого цвета
7. Кнопка удаления другого цвета


![Image](https://user-images.githubusercontent.com/114990952/207801651-1066d552-70d5-41ba-821f-caad9a0ede57.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801650-9566f074-cc9a-4b10-b331-4845f78383f2.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801647-6cc93ba3-922a-489b-a1a9-db65a73e8749.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801645-80b7a5f5-9742-463c-9369-8403080a9253.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801648-f8201c41-dd97-44cc-8012-29760556096a.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801646-ea248e78-b672-43eb-bfc6-cba42f7b3641.PNG)
![Image](https://user-images.githubusercontent.com/114990952/207801649-c74ccf18-c7e7-4a9d-9039-1bb405e83c24.PNG)

**Comment by vivalaakam** [comment]
![1](https://user-images.githubusercontent.com/758872/208593982-5ca76e3b-fc3a-4e28-a23e-71f6726d4d7f.png)
![2](https://user-images.githubusercontent.com/758872/208593995-3b5da30e-52a2-4f33-95cc-74b2fb589900.png)
![4](https://user-images.githubusercontent.com/758872/208593998-d73f219e-5783-4e75-b203-f95d4c26da68.png)
![5](https://user-images.githubusercontent.com/758872/208594002-270c11cb-31c3-4440-8bf0-78acfdf170ef.png)
![6](https://user-images.githubusercontent.com/758872/208594005-a9e4e541-b2f4-40ab-9f95-4b420a8e78f3.png)
![7](https://user-images.githubusercontent.com/758872/208594008-c0df02c3-b4de-45dc-927b-bc184b47ece4.png)

https://github.com/haqq-network/haqq-wallet/issues/684
