### ISSUE TITLE
[Анимация] Замена анимации

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#471]
Нужно заменить анимацию в нескольких местах
1. При создании аккаунта, на первой странице (https://www.dropbox.com/s/2otp68xrl0bbbmq/Animated%20about.json?dl=0)
2. На странице about (https://www.dropbox.com/s/2otp68xrl0bbbmq/Animated%20about.json?dl=0)
3. На разрешении блютуса (https://www.dropbox.com/s/5lx8xyvbpwzkudt/Animated%20Bluetooth.json?dl=0)
4. Заменить картинку в отклоненном блютусе https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=835%3A21807&t=7klEKhMiVnfwJk2f-4

**Comment by Poplavskiye** [comment]
**Tested on iOS 63**
1. Passed
2. Passed
3. Passed
4. @vivalaakam There is no Bluetooth icon (attachment below)


![Image](https://user-images.githubusercontent.com/98323599/205607420-c3be666a-9087-47ce-82d3-0f4e2bcd49ec.jpeg)
