### ISSUE TITLE
[UI / UX] "Your wallet" should be renamed to "Your account"

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#516]
**ENV**: iOS 59
**Conversation**: _https://haqqnetwork.slack.com/archives/C03RLCFMNCW/p1669812180534239_

_disorientation may occurs cause of main section calls "Your wallet" but there are no wallets inside. There are accounts._

"Wallet" should be renamed on placements below:
1. In the first page for newcomers
2. In the "Wallet" section

![Image](https://user-images.githubusercontent.com/98323599/204832055-f7de6a2a-1835-43e2-a30c-cb3e1ceaea7e.png)

**Comment by YuriySherbak** [comment]
Where I changed it
1. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=1%3A357&t=VcOrCzhwL71kE85I-4
2. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=312%3A7492&t=VcOrCzhwL71kE85I-4
3. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=55%3A689&t=VcOrCzhwL71kE85I-4
4. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=94%3A2167&t=VcOrCzhwL71kE85I-4
5. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=102%3A6217&t=VcOrCzhwL71kE85I-4
6. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=102%3A6227&t=VcOrCzhwL71kE85I-4
7. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=202%3A6799&t=VcOrCzhwL71kE85I-4
8. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=279%3A7410&t=VcOrCzhwL71kE85I-4
9. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=359%3A8280&t=VcOrCzhwL71kE85I-4
10. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=359%3A8401&t=VcOrCzhwL71kE85I-4
11. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=359%3A8450&t=VcOrCzhwL71kE85I-4
12. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=359%3A8434&t=VcOrCzhwL71kE85I-4
13. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=610%3A16653&t=VcOrCzhwL71kE85I-4
14. https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=835%3A22015&t=VcOrCzhwL71kE85I-4

**Comment by Poplavskiye** [comment]
Also change it on this page too

[IMG_95803AB48374-1](https://user-images.githubusercontent.com/98323599/205852841-4507305b-1e9b-42f4-b46e-31a27e389e11.jpeg)
