### ISSUE TITLE
[Connect account] Replace "Finish" to "Proceed"

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#559]
ENV: iOS 63 conversation link: _https://haqqnetwork.slack.com/archives/C03RLCFMNCW/p1670315378957879_

Change "Finish" to "Proceed" because of UX proposal 

![Image](https://user-images.githubusercontent.com/98323599/205867466-7a44055a-fe2a-4245-b798-1c19e5322abe.jpeg)

**Comment by YuriySherbak** [comment]
Done
