### ISSUE TITLE
[Верстка, Баги] Разные баги в верстке

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#562]
[Bugs] common

- [x] #676
- [x] #675
- [x] #674
- [x] #673 
- [x] #672
- [x] #671
- [x] #670
- [x] #669

**Comment by vivalaakam** [comment]
1. https://github.com/haqq-network/haqq-wallet/pull/608

**Comment by vivalaakam** [comment]
2. https://github.com/haqq-network/haqq-wallet/pull/609

**Comment by vivalaakam** [comment]
3. 8. https://github.com/haqq-network/haqq-wallet/pull/626
