### ISSUE TITLE
provider form

### ISSUE THREAD

**Issue by vivalaakam** [haqq-network/haqq-wallet#571]
design: https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=3810%3A59938&t=qdOX0uUYZN8pTnVW-4

**Comment by kioqq** [comment]
**Field | Placeholder**

Name  | Haqq Network
Chain ID | haqq_11235-1
Cosmos RPC | https://rpc.cosmos.haqq.network/
EVM RPC | https://rpc.eth.haqq.network/
EVM Explorer | https://explorer.haqq.network/
