### ISSUE TITLE
[Staking] Markup ain't fit to design

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#575]
**ENV**: iOS 65, iPhone 13 

**Expected result:** https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=3076%3A52776&t=QY6P9h7t6LuQbIAa-4

Actual result:

![Image](https://user-images.githubusercontent.com/98323599/206133404-d90d72b2-352a-4105-9682-18cfedc483f0.jpeg)

**Comment by vivalaakam** [comment]
It depends on screen width.
