### ISSUE TITLE
[Баг] Страница изменения имени аккаунта

### ISSUE THREAD

**Issue by YuriySherbak** [haqq-network/haqq-wallet#611]
1. В странице другой инпут (нет заголовка) https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=2550%3A80466&t=JwyXsJSadM96zW8o-4
2. Нет отмены и нет сохранения

![Image](https://user-images.githubusercontent.com/114990952/207056729-5b435ea4-152a-4c8c-a407-bc9a42c51c2a.jpeg)

**Comment by vivalaakam** [comment]
fixed by https://github.com/haqq-network/haqq-wallet/pull/606
