### ISSUE TITLE
[welcome] connect button size

### ISSUE THREAD

**Issue by gHashTag** [haqq-network/haqq-wallet#630]
кнопка connect должна быть такого же размера как create wallet

![image](https://user-images.githubusercontent.com/6774813/207599419-3179d676-5c7e-4dbe-bbdc-ccababf96ebf.jpeg)

**Comment by vivalaakam** [comment]
У всех кнопок уже проставлены размеры https://github.com/haqq-network/haqq-wallet/pull/608
