### ISSUE TITLE
Fix texts

### ISSUE THREAD

**Issue by vivalaakam** [haqq-network/haqq-wallet#652]
https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=0%3A1&t=6mkWzsVwMFjEwN98-0

see comments #14-#37

**Comment by gHashTag** [comment]
it's not clear at all what they want (the link to the design will not enter on a specific screen; there are no comments in #14 #37)
