### ISSUE TITLE
[Stake] No transaction history for Stake transaction

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#714]
ENV: Android release version
Steps:
1. Navigate to Stake, click on "Validators"
2. Select validator and click delegate and select an account
3. input amount and press "Delegate"

Expected result: Delegate is completed. Verify that you able to see your staked Validator. There is new transaction in History
Actual result:  Delegate is completed. Verify that you able to see your staked Validator. There is no this transaction in History

**Comment by parametre24** [comment]
![image](https://github.com/haqq-network/haqq-wallet/assets/138179016/a5e64946-e87e-4591-8879-af2caa8f86cd)sorun var

**Comment by ragozin-nikita** [comment]
Issue is too old, please try again.
