### ISSUE TITLE
[Ledger] Unable to reject selecting account request from Ledger

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#774]
**ENV**: iOS 85, Ledger Nano X

**Steps**: 

1. Connect Ledger via bluetooth
2. Select account from list
3. Reject selecting account request from Ledger by "Reject" button 

**Expected result:** "Request has been rejected" 
**Actual result:** Nothing happens until user confirm request

P.S. _There is no any design and validation for this case_

**Comment by kioqq** [comment]
Need release
