### ISSUE TITLE
[Delegate] Unable to sign a request from Ledger if it was locked

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#833]
ENV: Android 1.2 (70)

Steps: 

1. Connect Ledger to device and lock Ledger after
2. Navigate to Staking and select any Validator
3. Click on Delegate and select any available Ledger account 
4. Select amount and press Preview

Expected result: Ledger receiver the request from application. User able to sign it
Actual result: Ledger ain't received the request from application

**Comment by ragozin-nikita** [comment]
Hi, all issues with Ledger was fixed.
