### ISSUE TITLE
[Send] user can credit money to the same wallet from which it is sent

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#855]
**ENV**: iOS 108

**Steps**: 

1. Select account, click on Send
2. Input account address from which it is sent
3. Input amount
4. Click on Preview and proceed a transaction

**Expected result:** Validation appears: "You cannot send tokens to this account"
**Actual result:** Tokens sent, whole account amount stayed still exclude fees.

**Comment by ragozin-nikita** [comment]
Hi, we checked the app and this problem is no longer relevant.
