### ISSUE TITLE
[Import account] Recovery button are drops down by clickin' on it

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#873]
**ENV**: iOS 113 build 

**Steps**: 

1. Navigate to import wallet
2. Paste the import phrase and click to "Recovery" button

**Expected result:** Account recovery progress is in the progress 
**Actual result:** "Recovery" button are drops down by clickin' on it

**Comment by ragozin-nikita** [comment]
Hi, we checked the app and this problem is no longer relevant.
