### ISSUE TITLE
[Create Acc] Create account button is non-clickable

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#976]
ENV: iOS 134

Steps:
1. Navigate to "Add account" section
2. Click on "Import" and select "Custom network"
3. Enter non-existent email end press "ok"
4. After app does not found your account click on "Create Account"

Expected result: Button is clickable 
Actual result: Button is non-clickable

![Image](https://user-images.githubusercontent.com/98323599/228163757-5aeb75d9-ac07-487b-ac0d-941327b88d17.PNG)

**Comment by ragozin-nikita** [comment]
Hi, we checked the app and this problem is no longer relevant.
