### ISSUE TITLE
[Backup] When backup is succeed "backup" window displays

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/haqq-wallet#977]
ENV: iOS 134

Steps: 
1. Download app, create an account with no social login
2. Navigate to account backup and follow the instructions

Expected result: After backup is succeed main wallet menu is opened 
Actual result: After backup is succeed  "Backup" window is opened

**Comment by ragozin-nikita** [comment]
Hi, we checked the app and this problem is no longer relevant.
